### ISSUE TITLE
Please add linkable button

### ISSUE THREAD

**Issue by ivenkatraj** [Harry260/WhatsApp-Plus#2]
This is not an issue but i would like to request you to add an clickable link in you whatsapp-plus rather than text.
![image](https://user-images.githubusercontent.com/64081780/193302288-be60f1e0-35bf-48f6-8d7e-03a68f899502.png)

Like this👇👇
![image](https://user-images.githubusercontent.com/64081780/193302526-b1cc65f4-9161-4fdb-883e-b78b1dc4fbea.png)

**Comment by Harry260** [comment]
I don't think that's possible right now, as the library it uses right now don't have that feature. But i will try 👍🏻
